build:
	mkdir -p functions
	GOOS=linux
	GOARCH=amd64
	GOBIN=${PWD}/functions go get ./...
	env GOOS=linux GOARCH=amd64 go build -o ./functions/ ./...

build-local:
	mkdir -p functions
	GOBIN=${PWD}/functions go get ./...
	GOBIN=${PWD}/functions go install ./...